overrides:
  ceph:
    log-ignorelist:
    - but it is still running
    - overall HEALTH_
    - \(OSDMAP_FLAGS\)
    - \(PG_
    - \(OSD_
    - \(OBJECT_
    - \(POOL_APP_NOT_ENABLED\)
  ceph:
    conf:
      global:
        debug ms: 20
        debug auth: 20
        debug monc: 20
tasks:
- workunit:
    clients:
      client.0:
        - rados/test_python.sh
